In [1]:
import os


In [2]:
import numpy as np


In [3]:
import earthpy as et


In [4]:
monthly_precip_url = 'https://ndownloader.figshare.com/files/12565616'


In [5]:
et.data.get_data(url=monthly_precip_url)


'/home/codespace/earth-analytics/data/earthpy-downloads/avg-monthly-precip.txt'

In [6]:
precip_2002_2013_url = 'https://ndownloader.figshare.com/files/12707792'


In [7]:
et.data.get_data(url=precip_2002_2013_url)


'/home/codespace/earth-analytics/data/earthpy-downloads/monthly-precip-2002-2013.csv'

In [8]:
os.chdir(os.path.join(et.io.HOME, 'earth-analytics'))


In [9]:
fname = os.path.join("data", "earthpy-downloads",
                     "avg-monthly-precip.txt")

In [10]:
avg_monthly_precip = np.loadtxt(fname)


In [11]:
print(avg_monthly_precip)


[0.7  0.75 1.85 2.93 3.05 2.02 1.93 1.62 1.84 1.31 1.39 0.84]


In [12]:
fname = os.path.join("data", "earthpy-downloads",
                     "monthly-precip-2002-2013.csv")

In [13]:
precip_2002_2013 = np.loadtxt(fname, delimiter = ",")


In [14]:
print(precip_2002_2013)


[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]


In [15]:
avg_monthly_precip.ndim


1

In [16]:
precip_2002_2013.ndim


2

In [17]:
precip_2002_2013.shape


(2, 12)

In [18]:
avg_monthly_precip.shape

(12,)

In [19]:
print(avg_monthly_precip)


[0.7  0.75 1.85 2.93 3.05 2.02 1.93 1.62 1.84 1.31 1.39 0.84]


In [20]:
avg_monthly_precip *= 25.4


In [21]:
print(avg_monthly_precip)


[17.78  19.05  46.99  74.422 77.47  51.308 49.022 41.148 46.736 33.274
 35.306 21.336]


In [22]:
print(precip_2002_2013)


[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]


In [23]:
precip_2002_2013 *= 25.4


In [24]:
print(precip_2002_2013)


[[ 27.178  11.176  38.1     5.08   81.28   29.972   2.286  36.576  38.608
   61.976  19.812   0.508]
 [  6.858  28.702  43.688 105.156  67.564  15.494  26.162  35.56  461.264
   56.896   7.366  12.7  ]]


In [25]:
precip_list = [0.70, 0.75, 1.85, 2.93, 3.05, 2.02, 
              1.93, 1.62, 1.84, 1.31, 1.39, 0.84]

In [26]:
precip_list *=  25.4


TypeError: can't multiply sequence by non-int of type 'float'

In [27]:
mean_avg_precip = np.mean(avg_monthly_precip)


In [28]:
print("mean average monthly precipitation:", mean_avg_precip)


mean average monthly precipitation: 42.820166666666665


In [29]:
median_avg_precip = np.median(avg_monthly_precip)


In [30]:
print("median average monthly precipitation:", median_avg_precip)


median average monthly precipitation: 43.942


In [31]:
print("minimum average monthly precipitation:", np.min(avg_monthly_precip))


minimum average monthly precipitation: 17.779999999999998


In [32]:
print("maximum average monthly precipitation:", np.max(avg_monthly_precip))



maximum average monthly precipitation: 77.46999999999998


In [33]:
print(precip_2002_2013)


[[ 27.178  11.176  38.1     5.08   81.28   29.972   2.286  36.576  38.608
   61.976  19.812   0.508]
 [  6.858  28.702  43.688 105.156  67.564  15.494  26.162  35.56  461.264
   56.896   7.366  12.7  ]]


In [34]:
print(np.max(precip_2002_2013, axis=0))


[ 27.178  28.702  43.688 105.156  81.28   29.972  26.162  36.576 461.264
  61.976  19.812  12.7  ]


In [35]:
precip_2002_2013_monthly_max = np.max(precip_2002_2013, axis=0)


In [36]:
type(precip_2002_2013_monthly_max)


numpy.ndarray

In [37]:
print(precip_2002_2013)

[[ 27.178  11.176  38.1     5.08   81.28   29.972   2.286  36.576  38.608
   61.976  19.812   0.508]
 [  6.858  28.702  43.688 105.156  67.564  15.494  26.162  35.56  461.264
   56.896   7.366  12.7  ]]


In [38]:
print(np.max(precip_2002_2013, axis=1))


[ 81.28  461.264]
